version: "3.1"
nlu:
- intent: train2
  examples: |
    - 不要
    - 不做練習
    - 下次再練習
- intent: out_of_scope
  examples: |
    - 考試的答案
    - 你喜歡看什麼卡通
    - 功課的答案
    - 幫我寫作業
- intent: deny
  examples: |
    - 還是很難過
    - 沒變好
    - 沒用
    - 沒幫助
    - 沒有
- intent: say_yes
  examples: |
    - 有
    - 學會了
    - 會了
    - 我會了
- intent: say_no
  examples: |
    - 還沒
    - 還要練習
    - 學不會
    - 還沒學會
    - 還要想一下
    - 還不會
- intent: addition3
  examples: |
    - 我會好好說話
    - 說話要有禮貌
    - 我能好好說話
    - 練習能好好說話
    - 練習有禮貌的說話
    - 做錯事的時候也會好好說話
- intent: reject
  examples: |
    - 找其他人玩
    - 自己玩
    - 找其他同學一起玩
    - 玩別的東西
    - 去玩別的遊戲
    - 找別人玩
- intent: affirm
  examples: |
    - 感覺變好了
    - 笑話好笑
    - 變開心了
    - 有變好
    - 變好了
    - 影片有趣
    - 有
    - 心情有變好
    - 笑話很好笑
    - 感覺變開心了
- intent: train
  examples: |
    - 練習
    - 我要練習
    - 都可以
    - 我想練習
    - 可以
    - 好
    - 好阿
    - 練習變好
    - 要練習
- intent: greet
  examples: |
    - 妳好
    - 你好
    - 晚安
    - 下午好
    - 午安
    - 嗨嗨
    - 嗨，機器人
    - 早安
    - 您好
    - hi
    - 嗨
- intent: addition1
  examples: |
    - 別人表現很好
    - 別人表現比我好的時候不高興
    - 同學表現比我好
    - 同學表現的很好
    - 別人有好表現時我可以怎麼做
    - 別人有好表現的時候我可以怎麼做
    - 同學的表現比我好
    - 同學有好表現
    - 我表現比別人不好
    - 羨慕別人表現好
    - 別人表現好的時候我可以怎麼做
    - 別人表現好的時候
- intent: addition2
  examples: |
    - 想要跟別人玩可以怎麼做？
    - 想邀請同學一起玩
    - 邀請同學一起玩
    - 想跟同學一起玩
    - 想加入同學一起玩
    - 跟別人說要一起玩
    - 想跟別人玩我可以怎麼做？
    - 想找同學一起玩
    - 想跟別人玩
    - 邀請別人一起玩
    - 找朋友一起玩
    - 叫同學跟我一起玩
- intent: solve_all
  examples: |
    - 讚美別人
    - 稱讚別人的表現，
    - 我可以稱讚別人，下一次再換我
    - 稱讚她
    - 稱讚同學，自己也要多運動
    - 稱讚他的表現，自己也要多練習
    - 稱讚她的表現，自己也要認真跑
    - 稱讚他，自己也要認真跑
    - 稱讚她，自己也要多練習
    - 稱讚別人
    - 稱讚他的表現
    - 稱讚別人的表現
    - 稱讚同學
    - 我可以稱讚同學的表現
    - 讚美
    - 讚美他
- intent: happy
  examples: |
    - 還好
    - 今天很高興
    - 快樂
    - 今天覺得開心
    - 今天過得很快樂
    - 心情不錯
    - 今天很開心
    - 很棒
    - 有趣
    - 很開心
    - 很高興
    - 很讚
    - 高興
    - 還不錯
    - 今天過的很開心
    - 心情很好
    - 很好
- intent: solve2
  examples: |
    - 問他要不要一起玩
    - 要跟我一起去玩桌遊嗎
    - 可以一起玩嗎
    - 問他們能不能讓我加入
    - 我想一起玩
    - 問他要不要跟我一起玩
    - 問他們可不可以一起玩
    - 可以一起打球嗎
    - 問他們能不能加入
    - 可以一起跟你們玩嗎？
    - 問他們可不可以讓我加入
    - 問他們可不可以加入
    - 我會遵守規則，可以一起玩嗎？
    - 要跟我一起去打球嗎
    - 我可以加入嗎
    - 問他可以跟我一起玩嗎
    - 我想加入你們
    - 要跟我一起玩嗎
- intent: unhappy
  examples: |
    - 糟透了
    - 很不愉快
    - 很不爽
    - 悲傷
    - 今天過的不開心
    - 今天心情不好
    - 氣死
    - 很生氣
    - 難過
    - 過的不開心
    - 很不好
    - 今天很不爽
    - 生氣
    - 今天心情很差
    - 很難過
    - 不好
    - 今天很糟
    - 想哭
- intent: solve3
  examples: |
    - 我會排好隊
    - 我會調整自己的行為
    - 謝謝同學
    - 我會謝謝同學的提醒
    - 我會記得的！
    - 馬上做到老師提醒的事
    - 我會有禮貌的回應
    - 我會馬上把口罩戴好
    - 我會有禮貌的回應助理員
    - 調整自己的行為
    - 我會說謝謝同學！
    - 排好隊
    - 我會馬上做到助理員提醒的事
    - 我會謝謝老師，接受老師的提醒
    - 我會先跟同學道歉
    - 我會跟同學道歉
    - 謝謝老師的提醒
    - 我會說謝謝老師！
    - 我會謝謝同學，接受同學的提醒
    - 我會記得的
    - 我會謝謝助理員的提醒
    - 我會記得的，謝謝老師
    - 我會馬上做到老師提醒的事
    - 我會謝謝老師的提醒
    - 有禮貌的回應
- intent: choice
  examples: |
    - 你背得好完整
    - 你好厲害
    - 你的表現真好，太棒了
    - 你的速度好快
    - 哇！你真是太認真了！是大家的好榜樣
    - 你都寫對了耶！
    - 你好認真參與比賽，太棒了！
    - 跟他說你真厲害
    - 你真棒！這麼快就在完成作業了！
    - 你考了好高的分數，我覺得你好棒！
    - 跟他說你的表現真好
    - 跟他說你真厲害，能正確回答問題！
    - 你考了好高的分數
    - 跟他說你背的真好
    - 你的速度好快，真是厲害！
    - 表現得真好
    - 你好認真參與比賽，而且得到很好的成績，真是太棒了！
    - 你的表現 100分
    - 你的速度好快，一下子就衝到終點線了，真是厲害！
    - 跟他說你上課好認真
    - 恭喜你，你一定很努力
    - 你真厲害！能正確回答老師的問題
    - 你跑得好快
    - 跟他說你都寫對了耶
    - 你寫作業好認真
    - 你記的真清楚
    - 跟他說你的表現 100分
    - 你真厲害，能正確回答問題！
    - 跟他說你背誦的真流暢
    - 跟他說你好棒
    - 你表現得真好
    - 跟他說你表現的真棒
    - 你好棒
    - 你好強
    - 你上台都不會緊張，而且表現得很好呢！
    - 你都寫對了耶！100分！表現的真好！
    - 我會跟他說你好棒！
    - 跟他說你的速度好快
    - 你上課好認真
    - 你真的好棒
    - 你好厲害，我要向你學習
    - 跟他說你考了好高的分數
    - 你背誦的真流暢
    - 你真是太認真了
    - 跟他說你的速度好快，一下子就衝到終點線了，真是厲害！
    - 你今天好認真的在寫作業耶
    - 跟他說你背的好完整
    - 跟他說你比上次又更進步了！
    - 跟他說你表現的真好
    - 跟他說你考了好高的分數，我覺得你好棒！
    - 你背的真清楚
    - 大家都為你的好表現開心，你真是太厲害了！
    - 你的背誦真流暢！太厲害了！
    - 跟他說你好厲害可以正確回答老師的問題
    - 跟他說你好厲害
    - 恭喜你
    - 你跑的真快
    - 你今天好認真的在寫作業喔！
    - 我會說你好棒
    - 你真厲害
    - 說你好棒
    - 你跑得真快，體力真好
    - 跟他說你都寫對了耶！100分！表現的真好！
    - 跟他說 100分
    - 你表現的真棒
    - 跟他說你好厲害，我要向你看齊！
